### ISSUE TITLE
[FEATURE]: Caching in GitHub Actions

### ISSUE THREAD

**Issue by farisdurrani** [DSGT-DLP/Deep-Learning-Playground#855]
### Feature Name

Use caching in GitHub Actions builds

### Your Name

Faris Durrani

### Description

Our React and Python builds are relatively slow, and most of that time is in installing dependencies. We want to cut this time down using for example:

Python: https://mckornfield.medium.com/caching-python-installs-in-github-actions-8309e12a15e6
Node:
```yaml
name: Caching with npm
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
```
